import Pkg
Pkg.add("DifferentialEquations")
Pkg.add("Plots")
Pkg.add("Unitful")
Pkg.add("Distributions")
Pkg.add("DataFrames")
Pkg.add("CSV")
Pkg.add("SciMLBase")
Pkg.add("DiffEqBase")
Pkg.add("JSON")